// <auto-generated />
using System;
using EmpujeComunitario.MessageFlow.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EmpujeComunitario.MessageFlow.DataAccess.Migrations
{
    [DbContext(typeof(MessageFlowDbContext))]
    [Migration("20251021225616_createUserId")]
    partial class createUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.CancelledDonation", b =>
                {
                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrgId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RequestId", "OrgId");

                    b.ToTable("CancelledDonation");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.CancelledEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrgId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "OrgId");

                    b.ToTable("CancelledEvents");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("OfferId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("RequestId");

                    b.HasIndex("TransferId");

                    b.ToTable("DonationItems");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationOffer", b =>
                {
                    b.Property<Guid>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Create_user_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DonationOrganizationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OfferId");

                    b.ToTable("DonationOffers");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationRequest", b =>
                {
                    b.Property<Guid>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Creation_user_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("RequesterOrgId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestId");

                    b.ToTable("DonationRequests");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationTransfer", b =>
                {
                    b.Property<Guid>("TransferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DonationOrgId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TransferId");

                    b.HasIndex("RequestId");

                    b.ToTable("DonationTransfers");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.SolidaryEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTimeEvent")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("boolean");

                    b.Property<string>("NameEvent")
                        .HasColumnType("text");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventId");

                    b.ToTable("SolidaryEvents");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.VolunteerAdhesion", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("VolunteerId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("EventId", "VolunteerId");

                    b.ToTable("VolunteerAdhesions");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationItem", b =>
                {
                    b.HasOne("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationOffer", "Offer")
                        .WithMany("Donations")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationRequest", "Request")
                        .WithMany("Donations")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationTransfer", "Transfer")
                        .WithMany("Donations")
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Offer");

                    b.Navigation("Request");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationTransfer", b =>
                {
                    b.HasOne("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationRequest", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.VolunteerAdhesion", b =>
                {
                    b.HasOne("EmpujeComunitario.MessageFlow.DataAccess.Entities.SolidaryEvent", "Event")
                        .WithMany("Adhesions")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationOffer", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationRequest", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.DonationTransfer", b =>
                {
                    b.Navigation("Donations");
                });

            modelBuilder.Entity("EmpujeComunitario.MessageFlow.DataAccess.Entities.SolidaryEvent", b =>
                {
                    b.Navigation("Adhesions");
                });
#pragma warning restore 612, 618
        }
    }
}
